name: keeraya
description: keeraya app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  provider: ^6.0.3
  http: ^0.13.5
  html_unescape: ^2.0.0
  sqflite: ^2.1.0
  image_picker: ^0.8.6
  
  path: ^1.8.2
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^4.4.1+1
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  http_auth: ^1.0.1
  flutter_custom_tabs: ^1.0.4

  # multi_image_picker: ^4.8.1
  
  html: ^0.15.0
  google_maps_flutter: ^2.2.1
  photo_view: ^0.14.0
  url_launcher: ^6.1.6
  
  launch_review: ^3.0.1
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2
  
  facebook_audience_network: ^1.0.1
  
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  
  
  
  file_picker: ^5.2.0+1
  loader_overlay: ^2.1.0
  infinite_scroll_pagination: ^3.2.0
  razorpay_flutter: ^1.3.2
  # payu_money_flutter: ^0.0.3
  flutterwave_standard: ^1.0.4
  package_info_plus: ^1.4.3+1
  crypto: ^3.0.1
  #package to restart the app when user sign in or out
  flutter_phoenix: ^1.1.0
  advertising_id: ^2.3.0
  flutter_local_notifications: ^12.0.0
  purchases_flutter: ^4.3.0
  app_tracking_transparency: ^2.0.3

  # flutter_paystack: ^1.0.6
  # native_admob_flutter: ^1.5.0+1
  # dio: ^4.0.6
  # cupertino_icons: ^1.0.5
  # flutter_absolute_path: ^1.0.6
  # multi_image_picker: ^4.8.1
  # android_intent: ^2.0.2
  #flutter_native_admob: ^2.1.0+3
  # google_mobile_ads: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: 3.2.2
  flutter_native_splash: ^2.2.10+1
  flutter_launcher_icons: ^0.10.0

#dependency_overrides:
  # fix `packageRoot`compile error for iOS, because `path_provider` is using an old version of `platform`
#  platform: ^3.1.0 # overrides `path_provider`


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/clickforsale.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_loading.png