// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return android
          // ios
        ;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-54yt3O__jsDLSA_7ttyyV_-tBWKVzRc',
    appId: '1:1073919458848:web:9042e5ff49d989f7c98645',
    messagingSenderId: "1073919458848",
    projectId: 'keeraya-777ef',
    authDomain: 'keeraya-777ef.firebaseapp.com',
    databaseURL: 'https://keeraya-777ef-default-rtdb.firebaseio.com/',
    storageBucket: 'keeraya-777ef.appspot.com',
    measurementId: 'G-XS2JCNBHFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRfGvwSamgUt2uzApVgz1F1qY4Z62JNg',
    appId: '1:1073919458848:android:f52d9adb2aca5d69c98645',
    messagingSenderId: "1073919458848",
    projectId: 'keeraya-777ef',
    databaseURL: 'https://keeraya-777ef-default-rtdb.firebaseio.com/',
    storageBucket: 'keeraya-777ef.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCEDvNWD6fHE9yRcBClcKKyb0DC-pY56JU',
  //   appId: '1:618858142282:ios:601f7f429e99cee843a4b3',
  //   messagingSenderId: '618858142282',
  //   projectId: 'mark-classified',
  //   databaseURL: 'https://mark-classified-default-rtdb.firebaseio.com',
  //   storageBucket: 'mark-classified.appspot.com',
  //   androidClientId:
  //       '618858142282-0e78chvilfg8pfgrf8691tlerqsag5rb.apps.googleusercontent.com',
  //   iosClientId:
  //       '618858142282-1spr8lgdfch5336d4gin4i9j4pddblqf.apps.googleusercontent.com',
  //   iosBundleId: 'com.canderios.markclassified',
  // );
}
